server:
  port: 9007
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTH_SERVER_HOST:localhost}:9002
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:account}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    initialization-mode: always
    initialize: true
    continue-on-error: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  kafka:
    bootstrap-servers: http://${KAFKA_HOST:localhost}:9092

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
  tryItOutEnabled: true
  filter: true

leandro:
  openapi:
    dev-url: http://localhost:9007
    prod-url: https://appication-api.com
