server:
  port: 9002
spring:
  data:
    mongodb:
      user: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      uri: ${MONGO_URI}
leandro:
 api-user:
  host: ${API_USER_HOST}
 auth-server:
  host: ${AUTH_SERVER_HOST}