server:
  port: ${PORT:9002}
spring:
  data:
    mongodb:
      database: auth-server
      uri: ${MONGO_URI}
leandro:
  api-user:
    host: ${API_USER_HOST}
  auth-server:
    host: ${AUTH_SERVER_HOST}
