name: Build and Publish auth-server Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build_and_publish_api_person:
    name: Build and Publish Docker auth-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up the Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Copy aauth-server to build context
        run: cp -r authentication/auth-server $GITHUB_WORKSPACE

      - name: Build JAR without tests
        run: cd authentication/auth-server && mvn package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image (Root)
        run: |
          docker buildx create --use
          docker buildx build -t leandrobhmg/auth-server:${{ github.ref_name }} -f authentication/auth-server/Dockerfile authentication/auth-server --push
